### ISSUE TITLE
代码测试 | jzhmcoo1's blog

### ISSUE THREAD

**Issue by jzhmcoo1** [jzhmcoo1/jzhmcoo1.github.io#3]
https://jzhm.cool/2020/03/09/%E4%BB%A3%E7%A0%81%E6%B5%8B%E8%AF%95/ 

 测试 刚开始写博,贴个代码测试一下效果.

**Comment by Paradox315** [comment]
我爬了

**Comment by jzhmcoo1** [comment]
别🐴了大佬放过我> @Paradox315
> 我爬了
